// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { supabase as mockSupabase } from "./client";

// Demo Mode: Bypass RLS by using the mocked client directly.
// The actual service role client requires valid env variables, which we skip in demo.
export const supabaseAdmin = mockSupabase;
